const express=require('express');
const path=require('path');const jwt=require('jsonwebtoken');const sqlite3=require('sqlite3').verbose();
const app=express(),PORT=3000,SECRET=process.env.JWT_SECRET||'cambia-esta-clave-en-produccion';
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const db=new sqlite3.Database(path.join(__dirname,'database.db'));
db.serialize(()=>{db.run('PRAGMA foreign_keys = ON');db.run(`CREATE TABLE IF NOT EXISTS towers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE)`);db.run(`CREATE TABLE IF NOT EXISTS apartments(id INTEGER PRIMARY KEY AUTOINCREMENT,number TEXT NOT NULL,tower_id INTEGER NOT NULL,UNIQUE(number,tower_id),FOREIGN KEY(tower_id) REFERENCES towers(id) ON DELETE CASCADE)`);db.run(`CREATE TABLE IF NOT EXISTS vehicles(id INTEGER PRIMARY KEY AUTOINCREMENT,plate TEXT NOT NULL UNIQUE,brand TEXT NOT NULL,color TEXT NOT NULL,observations TEXT DEFAULT '')`);db.run(`CREATE TABLE IF NOT EXISTS news(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT DEFAULT '',apartment_id INTEGER,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(apartment_id) REFERENCES apartments(id) ON DELETE CASCADE)`)});
function auth(req,res,next){const token=(req.headers.authorization||'').replace('Bearer ','');if(!token)return res.status(401).json({error:'Token requerido'});jwt.verify(token,SECRET,(e,u)=>{if(e)return res.status(403).json({error:'Token inválido'});req.user=u;next()})}
function clean(v){return typeof v==='string'?v.trim():v}
app.post('/api/login',(req,res)=>{if(req.body.username==='admin'&&req.body.password==='123456')return res.json({success:true,token:jwt.sign({username:'admin'},SECRET,{expiresIn:'24h'})});res.status(401).json({success:false,message:'Credenciales inválidas'})});
const specs={towers:{table:'towers',fields:['name'],required:['name']},apartments:{table:'apartments',fields:['number','tower_id'],required:['number','tower_id']},vehicles:{table:'vehicles',fields:['plate','brand','color','observations'],required:['plate','brand','color']},news:{table:'news',fields:['title','description','apartment_id'],required:['title']}};
app.get('/api/towers',auth,(q,s)=>db.all('SELECT * FROM towers ORDER BY name',(e,r)=>e?s.status(500).json({error:e.message}):s.json(r)));
app.get('/api/apartments',auth,(q,s)=>db.all('SELECT a.*,t.name tower_name FROM apartments a JOIN towers t ON t.id=a.tower_id ORDER BY t.name,a.number',(e,r)=>e?s.status(500).json({error:e.message}):s.json(r)));
app.get('/api/vehicles',auth,(q,s)=>{let p=clean(q.query.plate||'').toUpperCase();db.all('SELECT * FROM vehicles '+(p?'WHERE plate LIKE ? ':'')+'ORDER BY plate',p?['%'+p+'%']:[],(e,r)=>e?s.status(500).json({error:e.message}):s.json(r))});
app.get('/api/news',auth,(q,s)=>db.all('SELECT n.*,a.number apartment_number,t.name tower_name FROM news n LEFT JOIN apartments a ON a.id=n.apartment_id LEFT JOIN towers t ON t.id=a.tower_id ORDER BY n.created_at DESC',(e,r)=>e?s.status(500).json({error:e.message}):s.json(r)));
for(const [key,x] of Object.entries(specs)){const base='/api/'+key;app.post(base,auth,(q,s)=>{let b={...q.body};if(key==='vehicles')b.plate=clean(b.plate).toUpperCase();for(const f of x.required)if(!b[f]&&b[f]!==0)return s.status(400).json({error:'Campos obligatorios incompletos'});let vals=x.fields.map(f=>clean(b[f])??null);db.run(`INSERT INTO ${x.table}(${x.fields.join(',')}) VALUES(${x.fields.map(()=>'?')})`,vals,function(e){if(e)return s.status(e.message.includes('UNIQUE')?400:500).json({error:e.message.includes('UNIQUE')?'El registro ya existe':e.message});s.status(201).json({id:this.lastID,...b})})});app.put(base+'/:id',auth,(q,s)=>{let b={...q.body};if(key==='vehicles')b.plate=clean(b.plate).toUpperCase();for(const f of x.required)if(!b[f]&&b[f]!==0)return s.status(400).json({error:'Campos obligatorios incompletos'});let vals=x.fields.map(f=>clean(b[f])??null);db.run(`UPDATE ${x.table} SET ${x.fields.map(f=>f+'=?').join(',')} WHERE id=?`,[...vals,q.params.id],function(e){if(e)return s.status(e.message.includes('UNIQUE')?400:500).json({error:e.message});s.json({success:true})})});app.delete(base+'/:id',auth,(q,s)=>db.run(`DELETE FROM ${x.table} WHERE id=?`,q.params.id,function(e){if(e)return s.status(500).json({error:e.message});s.json({success:true})}))}
app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'public/index.html')));app.listen(PORT,()=>console.log(`http://localhost:${PORT}`));